### ISSUE TITLE
Race Condition for Cloudtrail resource

### ISSUE THREAD

**Issue by MetricMike** [zoitech/terraform-aws-account#5]
Occasionally seeing an apply fail with:

```
aws_s3_bucket.cloudtrail_bucket: Creating...
aws_s3_bucket.cloudtrail_bucket: Creation complete
aws_cloudtrail.global_Default: Creating...
aws_s3_bucket_policy.cloudtrail_bucket_policy: Creating...
aws_s3_bucket_policy.cloudtrail_bucket_policy: Creation complete

aws_cloudtrail.global_Default: InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket
```

A re-plan and re-apply succeeds. It looks like the `aws_cloudtrail` resource has a dependency on `aws_s3_bucket_policy`, but terraform isn't detecting that on its own.

Adding a `depends_on` argument would be one way to fix, but wanted to ask before making a PR.

**Comment by derBroBro** [comment]
I think the issue happens as the trail has just a dependency for the bucket itself. 
In theory the trail and policy creation can happen in the same time. To solve this I think a dependency of the trail on the aws_s3_bucket_policy.cloudtrail_bucket_policy make sense.
It would be great if you can create a PR 😄
